house_pricing:
  train_dataset: C:\Slava\spbu-ai-fundamentals\files\house_prices\train.csv
  test_dataset: C:\Slava\spbu-ai-fundamentals\files\house_prices\test.csv
classification:
  wdbc: C:\Slava\spbu-ai-fundamentals\files\wdbc\data.csv
  mushrooms: C:\Slava\spbu-ai-fundamentals\files\mushrooms\mushrooms.csv
clustering:
  flowcytometry: C:\Slava\spbu_ai_fundamentals/flow_cytometry
